### ISSUE TITLE
Add total power consumption on Harvi device

### ISSUE THREAD

**Issue by bisand** [bisand/net.biseth.myenergi#12]
Add total power consumption to Harvi. Also add possibility to select how the power consumption should be calculated as a setting.

**Comment by Marlark** [comment]
Hey Andrè

Installed 1.7.2

I think you need to add a exclution function to the harvi so it is possible to remove it from the energi page calc and also make a option to make it be tagged as the home total unit.

// Teddy

**Comment by bisand** [comment]
Good point @Marlark. I didn’t think about that. Any good suggestions for doing that?
I thought about adding energy -> cumulative to its capability, but not sure if that will give the desired result.
I’m open for suggestions..

**Comment by Marlark** [comment]
I have seen those 2 functions in other apps. Ill look into how they are done during the day for you. I think your going to need to put in both. They should be fairly simple sins it is pure homey energi functions. In my own case i need to exclude them sins i use a tibber pulse p1 to pull the cumulative energy use from the P1 han port on my house meter.

// Teddy



Skickat från min Galaxy



-------- Originalmeddelande --------
Från: André Biseth ***@***.***>
Datum: 2022-10-10 06:00 (GMT+01:00)
Till: "bisand/net.biseth.myenergi" ***@***.***>
Kopia: Marlark ***@***.***>, Mention ***@***.***>
Ämne: Re: [bisand/net.biseth.myenergi] Add total power consumption on Harvi device (Issue #12)


Good point @Marlark<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarlark&data=05%7C01%7C%7C90665a8df43c4370683d08daaa73e7f5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638009712035419701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=i0TGIP94gdxldengPkUjd8%2BeDvVaAto5biJ2FDbbU1Q%3D&reserved=0>. I didn’t think about that. Any good suggestions for doing that?
I thought about adding energy -> cumulative to its capability, but not sure if that will give the desired result.
I’m open for suggestions..

**Comment by bisand** [comment]
I just did some testing and it seems like adding the cumulative flag in the capabilities will give us the desired result. I'll publish a new test version so you can test it with your setup.

Thanks!

**Comment by bisand** [comment]
The new [test version](https://homey.app/a/net.biseth.myenergi/test/) is published and ready to be tested.

**Comment by Marlark** [comment]
Installed 1.7.3 and see that it works nicely. I did think on one thing and i am not shure how or even if it should be solved as you can see on the picture bellow the solar harvi is a negative value and it should be considering it draws power from the grid however it should be added as a cost in the total when it aint producing/exporting and just drawing from the grid. I did have a idea thow and that is to add a negative detection and put it in a seperate device as a normal sensor  inverting it and add it as a normal meter cost.

[cid:storage_emulated_0_DCIM_Screenshots_Screenshot_20221010-073815_Homey_jpg_1665380574912]

// Teddy

Skickat från min Galaxy



-------- Originalmeddelande --------
Från: André Biseth ***@***.***>
Datum: 2022-10-10 06:52 (GMT+01:00)
Till: "bisand/net.biseth.myenergi" ***@***.***>
Kopia: Marlark ***@***.***>, Mention ***@***.***>
Ämne: Re: [bisand/net.biseth.myenergi] Add total power consumption on Harvi device (Issue #12)


The new test version<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhomey.app%2Fa%2Fnet.biseth.myenergi%2Ftest%2F&data=05%7C01%7C%7C7834ec78a032421c1a7d08daaa7b2d5d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638009743254267315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Kcd7imu6NCQeWJxIJb47oHoTQzzHIbt2wm9XoYPB1dA%3D&reserved=0> is published and ready to be tested.

**Comment by bisand** [comment]
Not quite sure if I understand. Your screenshot is not showing. Can you try to post the screenshot one more time?

**Comment by Marlark** [comment]
![Screenshot_20221010-073815_Homey](https://user-images.githubusercontent.com/8781715/194810826-bdb2f66e-8899-47b5-9543-004a0da50df9.jpg)

Sent a email reply on the message ... apparently it dont add the file.. Anyway here it is ;)

Was thinking on testing my idea out with the app Device Capabilities dont know if i can manipulate a virtual device enouph for it.

// Ted

**Comment by bisand** [comment]
Ok, I understand. Let's try to come up with a good solution. Here is some documentation that might lead us in the right direction. https://apps.developer.homey.app/the-basics/devices/energy#generating-devices

**Comment by Marlark** [comment]
Read this in the document

Homey will show this device separately in the UI. You should provide the generated power as a positive value. When providing a negative value, e.g. -13 watt, Homey assumes the solar panel is currently consuming instead of generating energy.

Looks like there is some type of automatic thing there  for solar.

Maybe we should make it possible to tag a harvi as a solar system in a switch wish sets a harvi with the solarpanel capability then it should solv the above. However we will end upp with issues together with the solarpanel apps that many have. Sins there is no way to turn the energi capability off in those.

The harvi is more direct and acurate in time compared to the solar panel app sins it lags behind so to say.

In that regard i would probably like to have the above ability. And then read the production value strait of the solar system. But there are those that also pull data strait of their converters and would like to have that as their primary source of data.

// Ted


Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: André ***@***.***>
Skickat: den 10 oktober 2022 09:15
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [bisand/net.biseth.myenergi] Add total power consumption on Harvi device (Issue #12)


Ok, I understand. Let's try to come up with a good solution. Here is some documentation that might lead us in the right direction. https://apps.developer.homey.app/the-basics/devices/energy#generating-devices<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.developer.homey.app%2Fthe-basics%2Fdevices%2Fenergy%23generating-devices&data=05%7C01%7C%7Ccbfb8789ff6742eab4a608daaa8f3e85%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638009829444934111%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dTwOSr9lwzNCINeE2xvM3NPEIhMVsJf7flx4cASPY0A%3D&reserved=0>

**Comment by bisand** [comment]
@Marlark, it seems like we have to do some more testing around that. The current version is now submitted for certification and is waiting for approval@homey. Meanwhile I will try to do some local testing. I will get back to you as soon as I have something ready for testing.
If you happen to find any good examples out there, please let me know.
Thanks for the help so far!

**Comment by Marlark** [comment]
Do that … im going to play around with that device capability thing and see if that is doable in some manor to invert the negative to a consumtion value.

// Ted

Skickades från E-post<https://go.microsoft.com/fwlink/?LinkId=550986> för Windows

Från: André ***@***.***>
Skickat: den 10 oktober 2022 10:31
Till: ***@***.***>
Kopia: ***@***.***>; ***@***.***>
Ämne: Re: [bisand/net.biseth.myenergi] Add total power consumption on Harvi device (Issue #12)


@Marlark<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMarlark&data=05%7C01%7C%7C642013be1f7d402ea25608daaa99c2d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638009874613522785%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ooj1s6s3%2BKbbAHgZTDmBYPncPr8JY735Ycs0VcUI3jY%3D&reserved=0>, it seems like we have to do some more testing around that. The current version is now submitted for certification and is waiting for ***@***.*** Meanwhile I will try to do some local testing. I will get back to you as soon as I have something ready for testing.
If you happen to find any good examples out there, please let me know.
Thanks for the help so far!

**Comment by Marlark** [comment]
Ok awsome :)

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
